### ISSUE TITLE
Fix printTree when a ns and a page have the almost same id

### ISSUE THREAD

**Issue by gturri** [gturri/nspages#120]
Steps to reproduce:

1. Start with an empty `sandbox:` namespace
2. create the page `sandbox:toto:tata` (with any arbitrary content)
3. create the page `sandbox:` with the content `<nspages -tree -subns -pagesInNs -r>`

This correctly displays something like
![image](https://user-images.githubusercontent.com/308601/145668540-c5b3220f-2f7b-4e77-a2ef-05becf5965b2.png)

4. create the page `sandbox:toto` (with any arbitrary content)
5. go back to `sandbox:`

This now displays something like 
![image](https://user-images.githubusercontent.com/308601/145668584-4182b95e-5a65-48a2-acb0-cb7041230ea2.png)

On this 2nd screenshot the issue is that the first element (`sandbox:toto:`) should appear as on the first screenshot (i.e. as a link)

**Comment by gturri** [comment]
It's fixed in nspages v2021-12-11. 

In a nutshell: the issue was that in this situation Dokuwiki considers that the main page of the namespace `a:b:c:` is the page `a:b:c` (and not, as it's usually the case `a:b:c:start`).

We may note that in this case the page `a:b:c` represents both a page (of the namespace `a:b:`) and the namespace `a:b:c:`. Subsequently this page now appears twice in the rendered tree.

**Comment by gturri** [comment]
I reverted the fix because it broke more common trees rendering (likely when nspages is invoked from the root of the wiki)

**Comment by dregad** [comment]
Hello @gturri 

I just updated to nspages 2021-12-15, but I'm still seeing the behavior where the namespace's title is not rendered as shown in screenshot below

![image](https://user-images.githubusercontent.com/449891/161931015-e7f5d0cc-6689-4e56-a33d-f79557a2791b.png)

I created both _admin:finances_ and _admin:finances:start_ pages, but that makes no difference, the namespace is still not being rendered as a link.

That's my code
```
<nspages admin: -r -tree -h1 -textPages="" -title -exclude:[start,c_template]>
```

**Comment by gturri** [comment]
Hi,
I'm afraid I'm not able to reproduce the behavior described on the 1st post of this bug report. Perhaps it could be an issue with a cache. Could you please try to:
- delete the cache of dokuwiki (deleting the directories inside `data/cache` should be enough)
- delete the cache of your browser
and check if the issue still occurs.

If it still occurs then I think it is another issue and we'll have to figure out how I can reproduce it.
Btw, when is the id of the link "Finances" on your screenshot? Is it `admin:finances`?

**Comment by gturri** [comment]
Also, I'm thinking of something: I think that it does not matter that you created the page `admin:finances:start` because with `-exclude:[start,c_template]` you exclude page with id `start`. If the only "start" page you want to exclude is the current page you could try using `-exclude -exclude:c_template`.

**Comment by dregad** [comment]
Hello Guillaume, and thanks for the fast reply.

Clearing the cache did not help, unfortunately.

> when is the id of the link "Finances" on your screenshot? Is it `admin:finances`?

Yes

> If the only "start" page you want to exclude is the current page you could try using `-exclude -exclude:c_template`.

Actually nspages is called from the _sidebar_ page, so "start" is not the current page.

> I think it is another issue and we'll have to figure out how I can reproduce it.

I don't know if it's another issue, you tell me... To help reproduce, I followed the steps in https://github.com/gturri/nspages/issues/120#issue-1077434903 and I can reproduce the problem in the playground, as follows:

- Stucture (sitemap)
    ![image](https://user-images.githubusercontent.com/449891/162026675-bed3fe2f-f530-4d58-be48-24d5a61ab73c.png)
- Page `playground:nspagestest:finances:start` has just a H1 title reading "Finances start page"
- Page `playground:nspagestest:finances:test` has just a H1 title reading "Test"
- Page `playground:nspagestest:start` (note: I removed the `exclude:[start c_template]` for testing purposes
    ```
    <nspages playground:nspagestest: -r -tree -h1 -textPages="" -title>
    ```
    ![image](https://user-images.githubusercontent.com/449891/162028215-0edd6848-6394-4476-8bb1-623a1f3a3941.png)

Since `start` is the default namespace page, I would expect that the title of _playground:nspagestest:finances:start_ (i.e. `Finances start page`) shows as the header for the tree node in the output from nspages, linking to the actual page. 

But instead, I see gray text `playground:nspagestest:finances:` and the start page appears in the list of pages below the namespace.

I hope this helps you to understand better, if not let me know.

**Comment by gturri** [comment]
Thanks for this detailed description.

You should add those flags to have the behavior you want: `-subns -pagesInNs` (ie: `<nspages playground:nspagestest: -r -tree -h1 -textPages="" -title -subns -pagesInNs>`)

Explanation: the gray text `playground:nspagestest:finances:` is a node of the tree which represents a namespace. Without the `-subns` flag such nodes are not rendered. And once you add this flag you should also add `-pagesInNs` to have all those nodes rendered in the same tree.

**Comment by dregad** [comment]
> You should add those flags to have the behavior you want: `-subns -pagesInNs` (ie: `<nspages playground:nspagestest: -r -tree -h1 -textPages="" -title -subns -pagesInNs>`)

That did the trick ! Thanks a lot :smile:
